name: End-to-end tests

on: push

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      test-files: ${{ steps.parse.outputs.test-files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies and find all test files using glob pattern
      - name: Prepare tests
        run: |
          npm install
          # Use find command to find all Cypress test files in the project root directory
          # Adjust the glob pattern to match your test file naming convention
          echo ::set-output name=test-files::$(find . -name '*.spec.js' -o -name '*.test.js' | tr '\n' ',')
        id: parse

  test:
    runs-on: ubuntu-22.04
    needs: prepare
    strategy:
      matrix:
        spec: ${{ fromJson(needs.prepare.outputs.test-files) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies and run Cypress tests in parallel
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: ${{ matrix.spec }}
