name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cypress binary and node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm ci  # Use `npm ci` for reproducible builds
          npm install

      - name: Install Cypress
        run: |
          npx cypress install

      - name: Run Cypress tests
        run: |
          npx cypress run --record --key 67d2d553-e8df-4548-aa05-bc09aaa94c35

      # Optionally, you can add steps for additional tasks after running tests, such as deploying artifacts or notifications.
