name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Install npm dependencies
      - name: Install Dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run  # Assuming you have a script in your package.json to run Cypress tests
