name: Cypress Tests

on: [push, pull_request]  # Run the workflow on push and pull request events

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checkout the code from the repository
        
      - name: Install Dependencies and Run Cypress Tests
        run: |
          npm install  # Install project dependencies
          npx cypress run  # Run Cypress tests
