name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cypress binary and node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm ci  # Use `npm ci` for reproducible builds

      - name: Install Cypress
        run: |
          npx cypress install

      - name: Divide spec files into groups
        id: divide-specs
        run: |
          spec_files=$(find cypress/e2e -name '*.spec.js' -type f -print)
          mapfile -t specs_array < <(echo "$spec_files" | tr '\n' '\0' | xargs -0 -n 1 -P 0 printf "%s\n")
          echo "::set-output name=specs::${specs_array[*]}"
        shell: bash

      - name: Run Cypress tests in parallel
        run: |
          for spec in "${{ steps.divide-specs.outputs.specs }}"; do
            npx cypress run --record --key 67d2d553-e8df-4548-aa05-bc09aaa94c35 --spec "$spec" &
          done
          wait
        shell: bash
