name: Cypress Tests

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Cypress Binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install Dependencies and Run Cypress Tests
        run: |
          npm ci
          npx cypress install
          npx cypress run
