name: End-to-end tests

on: push

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      integration-tests: ${{ steps.parse.outputs.integration-tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies and parse test files for parallelization
      - name: Prepare tests
        run: |
          npm install
          # Run a script to find all test files and output them to a JSON file
          find /Users/khaja.dudekela/Documents/On\ Going/Demo/cypress/e2e -type f -name '*.js' > integration-tests.json
        id: parse

  test:
    runs-on: ubuntu-22.04
    needs: prepare
    strategy:
      matrix:
        spec: ${{ fromJson(needs.prepare.outputs.integration-tests) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies and run Cypress tests in parallel
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: ${{ matrix.spec }}
