name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]  # You can add more versions if needed for parallel execution

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Cypress Binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run --parallel --record --key 67d2d553-e8df-4548-aa05-bc09aaa94c35 --spec "cypress/e2e/**/*.cy.js"
